"""Export KB as a single portable markdown file for AI agent context windows."""

from __future__ import annotations

import re
from pathlib import Path

import yaml


def export_skill(
    entity_dir: Path,
    output_path: Path,
    title: str = "Domain Knowledge Base",
    max_tokens: int | None = None,
) -> dict[str, int]:
    """Export entities as a single markdown file optimized for LLM context windows.

    Returns dict with counts: entities, types, total_chars, estimated_tokens.
    """
    if not entity_dir.exists():
        msg = f"Entity directory not found: {entity_dir}"
        raise FileNotFoundError(msg)

    entities_by_layer: dict[str, list[dict]] = {}
    type_counts: dict[str, int] = {}

    for md_file in sorted(entity_dir.rglob("*.md")):
        raw = md_file.read_text(encoding="utf-8")
        fm, body = _parse_frontmatter(raw)
        if not fm:
            continue

        eid = fm.get("id", md_file.stem)
        name = fm.get("name", eid)
        etype = fm.get("type", md_file.parent.name)
        layer = _layer_for_type(etype)
        confidence = fm.get("confidence", 1.0)
        description = fm.get("description", "")
        status = fm.get("status", "active")

        rels = _extract_relationships(fm)
        overview = _extract_overview(body)

        entry = {
            "id": eid,
            "name": name,
            "type": etype,
            "description": description,
            "confidence": confidence,
            "status": status,
            "relationships": rels,
            "overview": overview,
        }

        entities_by_layer.setdefault(layer, []).append(entry)
        type_counts[etype] = type_counts.get(etype, 0) + 1

    total_entities = sum(len(v) for v in entities_by_layer.values())

    lines = [
        f"# {title}",
        "",
        f"> {total_entities} entities across {len(type_counts)} types. "
        f"Generated by Context Blocks.",
        "",
    ]

    # Type summary
    lines.append("## Entity Types")
    lines.append("")
    for etype, count in sorted(type_counts.items(), key=lambda x: -x[1]):
        lines.append(f"- **{_humanize_type(etype)}** ({count})")
    lines.append("")

    # Entities by layer
    layer_order = [
        "Structural", "Behavioral", "Reference",
        "Organizational", "Language", "Decision", "Other",
    ]

    budget = max_tokens * 4 if max_tokens else None
    current_chars = sum(len(line) for line in lines)

    for layer in layer_order:
        layer_entities = entities_by_layer.get(layer, [])
        if not layer_entities:
            continue

        layer_entities.sort(key=lambda e: (-e["confidence"], e["name"]))

        section_lines = [
            f"## {layer} Layer",
            "",
        ]

        exported_count = 0
        for e in layer_entities:
            entry_lines = _format_entity(e)

            if budget:
                entry_chars = sum(len(l) for l in entry_lines)
                if current_chars + entry_chars > budget:
                    remaining = len(layer_entities) - exported_count
                    section_lines.append(
                        f"*({remaining} more entities truncated due to token budget)*"
                    )
                    break
                current_chars += entry_chars

            section_lines.extend(entry_lines)
            exported_count += 1

        lines.extend(section_lines)

    content = "\n".join(lines)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")

    return {
        "entities": total_entities,
        "types": len(type_counts),
        "total_chars": len(content),
        "estimated_tokens": len(content) // 4,
    }


def _parse_frontmatter(raw: str) -> tuple[dict, str]:
    match = re.match(r"^---\n(.*?\n)---\n?(.*)", raw, re.DOTALL)
    if not match:
        return {}, raw
    try:
        fm = yaml.safe_load(match.group(1))
        return (fm if isinstance(fm, dict) else {}), match.group(2)
    except yaml.YAMLError:
        return {}, raw


REL_FIELDS = [
    "related_to", "depends_on", "owned_by", "deployed_on",
    "implements_capability", "consumes", "produces", "triggers",
    "triggered_by", "affects", "affected_by", "related_systems",
    "related_processes", "triggered", "published_by", "subscribed_by",
    "managed_by",
]


def _extract_relationships(fm: dict) -> list[str]:
    rels = []
    for field in REL_FIELDS:
        refs = fm.get(field)
        if not refs:
            continue
        if isinstance(refs, str):
            refs = [refs]
        label = field.replace("_", " ")
        for ref in refs:
            rels.append(f"{label}: {ref}")
    return rels


def _extract_overview(body: str) -> str:
    """Extract the Overview section from the body, trimmed to ~3 sentences."""
    lines = body.split("\n")
    in_overview = False
    overview_lines = []

    for line in lines:
        if line.strip().lower().startswith("## overview"):
            in_overview = True
            continue
        if in_overview and line.strip().startswith("## "):
            break
        if in_overview and line.strip():
            overview_lines.append(line.strip())

    text = " ".join(overview_lines)
    sentences = re.split(r'(?<=[.!?])\s+', text)
    return " ".join(sentences[:3])


def _format_entity(e: dict) -> list[str]:
    lines = [f"### {e['name']}"]
    lines.append(f"*{e['type']}* | confidence: {e['confidence']}")
    if e["description"]:
        lines.append(f"> {e['description']}")
    lines.append("")

    if e["overview"]:
        lines.append(e["overview"])
        lines.append("")

    if e["relationships"]:
        for rel in e["relationships"]:
            lines.append(f"- {rel}")
        lines.append("")

    return lines


def _humanize_type(etype: str) -> str:
    return etype.replace("-", " ").replace("_", " ").title()


LAYER_MAP = {
    "system": "Structural", "software-component": "Structural",
    "api": "Structural", "data-model": "Structural",
    "data-product": "Structural", "platform": "Structural",
    "process": "Behavioral", "business-event": "Behavioral",
    "domain-logic": "Behavioral",
    "reference-data": "Reference",
    "team": "Organizational", "persona": "Organizational",
    "capability": "Organizational", "offering": "Organizational",
    "external-party": "Organizational",
    "jargon-business": "Language", "jargon-tech": "Language",
    "decision": "Decision",
}


def _layer_for_type(etype: str) -> str:
    from context_blocks.ontology import get_active_ontology

    ont = get_active_ontology()
    if ont is not None:
        layer = ont.get_layer(etype)
        if layer and layer != "unknown":
            return layer.title()
    return LAYER_MAP.get(etype, "Other")
